#if !defined(AFX_MONTHVIEW_H__529DF0BE_1C03_4AA1_B555_51A48F59F109__INCLUDED_)
#define AFX_MONTHVIEW_H__529DF0BE_1C03_4AA1_B555_51A48F59F109__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CMonthView wrapper class

class CMonthView : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMonthView)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x232e456a, 0x87c3, 0x11d1, { 0x8b, 0xe3, 0x0, 0x0, 0xf8, 0x75, 0x4d, 0xa1 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetAppearance();
	void SetAppearance(long nNewValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	short GetDay();
	void SetDay(short nNewValue);
	BOOL GetDayBold(DATE dateIndex);
	void SetDayBold(DATE dateIndex, BOOL bNewValue);
	long GetDayOfWeek();
	void SetDayOfWeek(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH newValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	long GetHWnd();
	void SetHWnd(long nNewValue);
	DATE GetMaxDate();
	void SetMaxDate(DATE newValue);
	short GetMaxSelCount();
	void SetMaxSelCount(short nNewValue);
	DATE GetMinDate();
	void SetMinDate(DATE newValue);
	long GetMonth();
	void SetMonth(long nNewValue);
	unsigned long GetMonthBackColor();
	void SetMonthBackColor(unsigned long newValue);
	short GetMonthColumns();
	void SetMonthColumns(short nNewValue);
	short GetMonthRows();
	void SetMonthRows(short nNewValue);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	BOOL GetMultiSelect();
	void SetMultiSelect(BOOL bNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	short GetScrollRate();
	void SetScrollRate(short nNewValue);
	DATE GetSelEnd();
	void SetSelEnd(DATE newValue);
	DATE GetSelStart();
	void SetSelStart(DATE newValue);
	BOOL GetShowToday();
	void SetShowToday(BOOL bNewValue);
	BOOL GetShowWeekNumbers();
	void SetShowWeekNumbers(BOOL bNewValue);
	long GetStartOfWeek();
	void SetStartOfWeek(long nNewValue);
	unsigned long GetTitleBackColor();
	void SetTitleBackColor(unsigned long newValue);
	unsigned long GetTitleForeColor();
	void SetTitleForeColor(unsigned long newValue);
	unsigned long GetTrailingForeColor();
	void SetTrailingForeColor(unsigned long newValue);
	DATE GetValue();
	void SetValue(DATE newValue);
	DATE GetVisibleDays(short sIndex);
	void SetVisibleDays(short sIndex, DATE newValue);
	short GetWeek();
	void SetWeek(short nNewValue);
	short GetYear();
	void SetYear(short nNewValue);
	void ComputeControlSize(short Rows, short Columns, float* Width, float* Height);
	long HitTest(long x, long y, DATE* Date);
	void OLEDrag();
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MONTHVIEW_H__529DF0BE_1C03_4AA1_B555_51A48F59F109__INCLUDED_)
